spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/preapproved
    username: postgres
    password: postgres
    jpa:
      hibernate.ddl-auto: update
  kafka:
    bootstrap-servers:
      - localhost:9092